// SPDX-License-Identifier: BSD-3-Clause OR Apache-2.0
//
// Copyright (c) 2026 Witt Kung <witt.w.kung@gmail.com>
// All rights reserved.
//
// TTZip: High-performance native archiving and compression engine.

//! Comprehensive Bidirectional Differential Test Suite & 5-Dimension Oracle (Task 16.10).
//!
//! Validates zero-divergence and bit-exact interoperability against macOS / POSIX native CLI tools:
//! - System `bsdtar` (`/usr/bin/tar` - libarchive)
//! - System `bsdcpio` (`/usr/bin/cpio` - libarchive)
//! - System `unzip` / `zip` (`/usr/bin/unzip`, `/usr/bin/zip` - Info-ZIP / Apple)
//!
//! Test Dimensions:
//! 1. **Direction 1 (System -> TTZip)**:
//!    Archives created by system tools (`bsdtar`, `bsdcpio`, `zip`) are extracted by TTZip's
//!    `UnifiedArchiveOrchestrator` and `SecurePathExtractor`, verifying 100% extraction fidelity.
//! 2. **Direction 2 (TTZip -> System)**:
//!    Archives generated by TTZip (TAR, CPIO, ZIP) are extracted by native system CLI tools,
//!    asserting 0 warnings, 0 errors, and byte-exact roundtrip restoration.
//! 3. **5-Dimension Differential Oracle**:
//!    Strict assertions across Relative Path, Size, SHA-256 Checksum, POSIX Mode/Permissions,
//!    and Symlink Target.
//! 4. **Edge Cases**:
//!    Deep nested directories, empty files, empty directories, Unicode filenames (UTF-8/NFC),
//!    hardlinks, symlinks, and distinct permission masks (`0o755`, `0o644`, `0o444`).

use std::fs::{self, File};
use std::io::Write;
use std::os::unix::fs::{symlink, PermissionsExt};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use tempfile::TempDir;
use ttzip_engine::archive::unified::UnifiedArchiveOrchestrator;
use ttzip_engine::security::{SecurePathExtractor, SecurityFlags};
use ttzip_engine::testing::differential::{compare_manifests, scan_directory_tree};
use ttzip_engine::types::{
    TTZipArchiveFormat, TTZipCompressionLevel, TTZipCreateOptions, TTZipExtractOptions,
};

// MARK: - CLI Tool Discovery & Environment Helpers

const SYSTEM_TAR_PATH: &str = "/usr/bin/tar";
const SYSTEM_CPIO_PATH: &str = "/usr/bin/cpio";
const SYSTEM_UNZIP_PATH: &str = "/usr/bin/unzip";
const SYSTEM_ZIP_PATH: &str = "/usr/bin/zip";

/// Checks if a system CLI binary exists and is executable.
fn is_tool_available(path: &str) -> bool {
    let p = Path::new(path);
    p.exists() && p.is_file()
}

/// Helper RAII test sandbox for isolated bidirectional differential tests.
struct TestSandbox {
    _temp_dir: TempDir,
    root: PathBuf,
    source_dir: PathBuf,
    system_out_dir: PathBuf,
    ttzip_out_dir: PathBuf,
}

impl TestSandbox {
    fn new(prefix: &str) -> Self {
        let temp_dir = tempfile::Builder::new()
            .prefix(prefix)
            .tempdir()
            .expect("failed to create temporary test sandbox");
        let root = temp_dir.path().to_path_buf();
        let source_dir = root.join("src_tree");
        let system_out_dir = root.join("sys_extracted");
        let ttzip_out_dir = root.join("ttzip_extracted");

        fs::create_dir_all(&source_dir).expect("failed to create src_tree dir");
        fs::create_dir_all(&system_out_dir).expect("failed to create sys_extracted dir");
        fs::create_dir_all(&ttzip_out_dir).expect("failed to create ttzip_extracted dir");

        Self {
            _temp_dir: temp_dir,
            root,
            source_dir,
            system_out_dir,
            ttzip_out_dir,
        }
    }

    /// Recursively collects immediate child paths of the source directory.
    fn source_children(&self) -> Vec<PathBuf> {
        let mut paths = Vec::new();
        if let Ok(entries) = fs::read_dir(&self.source_dir) {
            for entry in entries.flatten() {
                paths.push(entry.path());
            }
        }
        paths.sort();
        paths
    }
}

// MARK: - Rich Multi-Layer Tree Generator

/// Populates `source_dir` with a multi-layered, heterogeneous file tree.
fn populate_complex_test_tree(sandbox: &TestSandbox) {
    let src = &sandbox.source_dir;

    // 1. Regular text file at root
    let root_txt = src.join("readme.txt");
    fs::write(&root_txt, b"TTZip System Differential Oracle Ground Truth Data\n").unwrap();
    fs::set_permissions(&root_txt, fs::Permissions::from_mode(0o644)).unwrap();

    // 2. Empty file
    let empty_file = src.join("empty.zero");
    File::create(&empty_file).unwrap();
    fs::set_permissions(&empty_file, fs::Permissions::from_mode(0o644)).unwrap();

    // 3. Executable script
    let bin_dir = src.join("bin");
    fs::create_dir_all(&bin_dir).unwrap();
    let script = bin_dir.join("run.sh");
    fs::write(&script, b"#!/bin/sh\necho \"Executing differential check\"\n").unwrap();
    fs::set_permissions(&script, fs::Permissions::from_mode(0o755)).unwrap();

    // 4. Read-only configuration file
    let conf_dir = src.join("config");
    fs::create_dir_all(&conf_dir).unwrap();
    let ro_conf = conf_dir.join("system.conf");
    fs::write(&ro_conf, b"[oracle]\nmode=strict_differential\nlevel=maximum\n").unwrap();
    fs::set_permissions(&ro_conf, fs::Permissions::from_mode(0o444)).unwrap();

    // 5. Deeply nested hierarchy (Depth 5)
    let deep_dir = src.join("deep").join("l1").join("l2").join("l3").join("l4");
    fs::create_dir_all(&deep_dir).unwrap();
    let deep_file = deep_dir.join("leaf_payload.dat");
    let mut large_pattern = Vec::with_capacity(32 * 1024);
    for i in 0..(32 * 1024) {
        large_pattern.push((i % 251) as u8);
    }
    fs::write(&deep_file, &large_pattern).unwrap();
    fs::set_permissions(&deep_file, fs::Permissions::from_mode(0o644)).unwrap();

    // 6. Empty directory
    let empty_dir = src.join("empty_folder");
    fs::create_dir_all(&empty_dir).unwrap();

    // 7. Unicode & Emoji filenames (NFC normalized UTF-8)
    let u_dir = src.join("unicode");
    fs::create_dir_all(&u_dir).unwrap();
    let u_file1 = u_dir.join("日本語_テスト_仕様書.txt");
    fs::write(&u_file1, "日本語UTF-8差分テストデータ：高精度検証".as_bytes()).unwrap();
    let u_file2 = u_dir.join("中文_苹果架构_🚀.md");
    fs::write(&u_file2, "# 苹果芯片原生微内核差分测试\n性能卓越！".as_bytes()).unwrap();

    // 8. Symbolic links
    let links_dir = src.join("links");
    fs::create_dir_all(&links_dir).unwrap();
    let link_to_readme = links_dir.join("symlink_to_readme.txt");
    symlink("../readme.txt", &link_to_readme).unwrap();

    let link_to_deep = links_dir.join("symlink_to_deep.dat");
    symlink("../deep/l1/l2/l3/l4/leaf_payload.dat", &link_to_deep).unwrap();

    // 9. Hardlinks (linking to root readme)
    let hardlink_file = src.join("hardlink_readme.txt");
    fs::hard_link(&root_txt, &hardlink_file).unwrap();
}

// MARK: - 5-Dimension Oracle Verification Helper

/// Validates that `actual_dir` exactly matches `expected_dir` across all 5 dimensions.
fn assert_differential_oracle_match(
    expected_dir: &Path,
    actual_dir: &Path,
    is_tar_format: bool,
    oracle_name: &str,
    format_name: &str,
) {
    let expected_manifest = scan_directory_tree(expected_dir)
        .unwrap_or_else(|e| panic!("failed scanning expected manifest at {:?}: {:?}", expected_dir, e));
    let actual_manifest = scan_directory_tree(actual_dir)
        .unwrap_or_else(|e| panic!("failed scanning actual manifest at {:?}: {:?}", actual_dir, e));

    let report = compare_manifests(
        &actual_manifest,
        &expected_manifest,
        is_tar_format,
        oracle_name,
        format_name,
    );

    if !report.is_passed {
        eprintln!("=======================================================");
        eprintln!("DIFFERENTIAL ORACLE DIVERGENCE DETECTED [{} / {}]", oracle_name, format_name);
        for (i, err) in report.divergence_errors.iter().enumerate() {
            eprintln!("  [{:02}] {}", i + 1, err);
        }
        if let Some(diff) = &report.hex_diff_output {
            eprintln!("--- Binary Hex Diff ---\n{}", diff);
        }
        eprintln!("=======================================================");
        panic!(
            "Differential Oracle failed with {} divergence errors between {:?} and {:?}",
            report.divergence_errors.len(),
            expected_dir,
            actual_dir
        );
    }

    assert!(report.is_passed);
    assert_eq!(report.divergence_errors.len(), 0);
}

// MARK: - Direction 1: System CLI -> TTZip Extraction Tests

#[test]
fn test_direction1_bsdtar_to_ttzip_differential() {
    if !is_tool_available(SYSTEM_TAR_PATH) {
        eprintln!("[SKIP] System bsdtar not found at {}, skipping test.", SYSTEM_TAR_PATH);
        return;
    }

    let sandbox = TestSandbox::new("ttzip_diff_d1_tar");
    populate_complex_test_tree(&sandbox);

    let tar_archive = sandbox.root.join("system_created.tar");

    // 1. Pack with system bsdtar (/usr/bin/tar -cf <tar_archive> .)
    let tar_status = Command::new(SYSTEM_TAR_PATH)
        .arg("-cf")
        .arg(&tar_archive)
        .arg(".")
        .current_dir(&sandbox.source_dir)
        .status()
        .expect("failed executing system bsdtar -cf");
    assert!(tar_status.success(), "system bsdtar creation failed");

    // 2. Extract with TTZip UnifiedArchiveOrchestrator
    let extract_opts = TTZipExtractOptions {
        preserve_permissions: true,
        overwrite_existing: true,
        ..Default::default()
    };
    UnifiedArchiveOrchestrator::extract_archive(&tar_archive, &sandbox.ttzip_out_dir, &extract_opts)
        .expect("TTZip extraction of system tar archive failed");

    // 3. 5-Dimension Oracle Differential Comparison
    assert_differential_oracle_match(
        &sandbox.source_dir,
        &sandbox.ttzip_out_dir,
        true,
        "bsdtar",
        "tar",
    );
}

#[test]
fn test_direction1_bsdcpio_to_ttzip_differential() {
    if !is_tool_available(SYSTEM_CPIO_PATH) {
        eprintln!("[SKIP] System bsdcpio not found at {}, skipping test.", SYSTEM_CPIO_PATH);
        return;
    }

    let sandbox = TestSandbox::new("ttzip_diff_d1_cpio");
    populate_complex_test_tree(&sandbox);

    let cpio_archive = sandbox.root.join("system_created.cpio");

    // 1. Pack with system bsdcpio (/usr/bin/cpio -o -H newc)
    let find_output = Command::new("find")
        .arg(".")
        .current_dir(&sandbox.source_dir)
        .output()
        .expect("failed executing find command");
    assert!(find_output.status.success(), "find command failed");

    let cpio_file = File::create(&cpio_archive).expect("failed creating cpio destination file");
    let mut cpio_child = Command::new(SYSTEM_CPIO_PATH)
        .arg("-o")
        .arg("-H")
        .arg("newc")
        .current_dir(&sandbox.source_dir)
        .stdin(Stdio::piped())
        .stdout(cpio_file)
        .spawn()
        .expect("failed spawning system bsdcpio -o");

    if let Some(mut stdin) = cpio_child.stdin.take() {
        stdin.write_all(&find_output.stdout).unwrap();
    }
    let cpio_status = cpio_child.wait().expect("failed waiting for bsdcpio");
    assert!(cpio_status.success(), "system bsdcpio archive creation failed");

    // 2. Extract with TTZip UnifiedArchiveOrchestrator
    let extract_opts = TTZipExtractOptions {
        preserve_permissions: true,
        overwrite_existing: true,
        ..Default::default()
    };
    UnifiedArchiveOrchestrator::extract_archive(&cpio_archive, &sandbox.ttzip_out_dir, &extract_opts)
        .expect("TTZip extraction of system cpio archive failed");

    // 3. 5-Dimension Oracle Differential Comparison
    assert_differential_oracle_match(
        &sandbox.source_dir,
        &sandbox.ttzip_out_dir,
        false,
        "bsdcpio",
        "cpio",
    );
}

#[test]
fn test_direction1_zip_to_ttzip_secure_extract_differential() {
    if !is_tool_available(SYSTEM_ZIP_PATH) {
        eprintln!("[SKIP] System zip not found at {}, skipping test.", SYSTEM_ZIP_PATH);
        return;
    }

    let sandbox = TestSandbox::new("ttzip_diff_d1_zip");
    populate_complex_test_tree(&sandbox);

    let zip_archive = sandbox.root.join("system_created.zip");

    // 1. Pack with system /usr/bin/zip -y -r -q <zip_archive> .
    let zip_status = Command::new(SYSTEM_ZIP_PATH)
        .arg("-y")
        .arg("-r")
        .arg("-q")
        .arg(&zip_archive)
        .arg(".")
        .current_dir(&sandbox.source_dir)
        .status()
        .expect("failed executing system zip");
    assert!(zip_status.success(), "system zip creation failed");

    // 2. Extract with TTZip Secure Sandbox Extractor
    let extract_opts = TTZipExtractOptions {
        preserve_permissions: true,
        overwrite_existing: true,
        ..Default::default()
    };
    UnifiedArchiveOrchestrator::extract_archive(&zip_archive, &sandbox.ttzip_out_dir, &extract_opts)
        .expect("TTZip extraction of system zip archive failed");

    // 3. Verify Sandbox Integrity with SecurePathExtractor
    let extractor = SecurePathExtractor::new(&sandbox.ttzip_out_dir, SecurityFlags::DEFAULT)
        .expect("SecurePathExtractor failed to initialize");
    let canonical_sandbox = fs::canonicalize(&sandbox.ttzip_out_dir).expect("canonicalize ttzip_out_dir failed");
    assert_eq!(extractor.sandbox_root(), canonical_sandbox.as_path());

    // 4. 5-Dimension Oracle Differential Comparison
    assert_differential_oracle_match(
        &sandbox.source_dir,
        &sandbox.ttzip_out_dir,
        false,
        "system_zip",
        "zip",
    );
}

// MARK: - Direction 2: TTZip Generation -> System CLI Extraction Tests

#[test]
fn test_direction2_ttzip_tar_to_bsdtar_differential() {
    if !is_tool_available(SYSTEM_TAR_PATH) {
        eprintln!("[SKIP] System bsdtar not found at {}, skipping test.", SYSTEM_TAR_PATH);
        return;
    }

    let sandbox = TestSandbox::new("ttzip_diff_d2_tar");
    populate_complex_test_tree(&sandbox);

    let ttzip_tar_path = sandbox.root.join("ttzip_generated.tar");
    let sources = sandbox.source_children();

    // 1. TTZip UnifiedArchiveOrchestrator creates TAR archive
    let create_opts = TTZipCreateOptions {
        format: TTZipArchiveFormat::Tar,
        level: TTZipCompressionLevel::Normal,
        ..Default::default()
    };
    UnifiedArchiveOrchestrator::create_archive(&sources, &ttzip_tar_path, &create_opts, 0)
        .expect("TTZip create_archive failed for TAR format");
    assert!(ttzip_tar_path.exists());

    // 2. System bsdtar extracts (/usr/bin/tar -xf <ttzip_tar_path> -C <system_out_dir>)
    let untar_output = Command::new(SYSTEM_TAR_PATH)
        .arg("-xf")
        .arg(&ttzip_tar_path)
        .arg("-C")
        .arg(&sandbox.system_out_dir)
        .output()
        .expect("failed executing system bsdtar -xf");

    let stderr = String::from_utf8_lossy(&untar_output.stderr);
    assert!(
        untar_output.status.success(),
        "system bsdtar failed to unpack TTZip archive: {}",
        stderr
    );
    assert!(stderr.is_empty(), "system bsdtar emitted warnings: {}", stderr);

    // 3. 5-Dimension Oracle Differential Comparison
    assert_differential_oracle_match(
        &sandbox.source_dir,
        &sandbox.system_out_dir,
        true,
        "bsdtar",
        "tar",
    );
}

#[test]
fn test_direction2_ttzip_cpio_to_bsdcpio_differential() {
    if !is_tool_available(SYSTEM_CPIO_PATH) {
        eprintln!("[SKIP] System bsdcpio not found at {}, skipping test.", SYSTEM_CPIO_PATH);
        return;
    }

    let sandbox = TestSandbox::new("ttzip_diff_d2_cpio");
    populate_complex_test_tree(&sandbox);

    let ttzip_cpio_path = sandbox.root.join("ttzip_generated.cpio");
    let sources = sandbox.source_children();

    // 1. TTZip UnifiedArchiveOrchestrator creates CPIO archive
    let create_opts = TTZipCreateOptions {
        format: TTZipArchiveFormat::Cpio,
        level: TTZipCompressionLevel::Store,
        ..Default::default()
    };
    UnifiedArchiveOrchestrator::create_archive(&sources, &ttzip_cpio_path, &create_opts, 0)
        .expect("TTZip create_archive failed for CPIO format");
    assert!(ttzip_cpio_path.exists());

    // 2. System bsdcpio extracts (/usr/bin/cpio -idmv < ttzip_cpio_path)
    let cpio_file = File::open(&ttzip_cpio_path).expect("failed opening generated cpio archive");
    let uncpio_child = Command::new(SYSTEM_CPIO_PATH)
        .arg("-idmv")
        .current_dir(&sandbox.system_out_dir)
        .stdin(cpio_file)
        .output()
        .expect("failed executing system bsdcpio -idmv");

    assert!(
        uncpio_child.status.success(),
        "system bsdcpio extraction failed: {}",
        String::from_utf8_lossy(&uncpio_child.stderr)
    );

    // 3. 5-Dimension Oracle Differential Comparison
    assert_differential_oracle_match(
        &sandbox.source_dir,
        &sandbox.system_out_dir,
        false,
        "bsdcpio",
        "cpio",
    );
}

#[test]
fn test_direction2_ttzip_zip_to_bsdunzip_differential() {
    if !is_tool_available(SYSTEM_UNZIP_PATH) {
        eprintln!("[SKIP] System unzip not found at {}, skipping test.", SYSTEM_UNZIP_PATH);
        return;
    }

    let sandbox = TestSandbox::new("ttzip_diff_d2_zip");
    populate_complex_test_tree(&sandbox);

    let ttzip_zip_path = sandbox.root.join("ttzip_generated.zip");
    let sources = sandbox.source_children();

    // 1. TTZip UnifiedArchiveOrchestrator creates streaming parallel ZIP
    let create_opts = TTZipCreateOptions {
        format: TTZipArchiveFormat::Zip,
        level: TTZipCompressionLevel::Normal,
        ..Default::default()
    };
    UnifiedArchiveOrchestrator::create_archive(&sources, &ttzip_zip_path, &create_opts, 0)
        .expect("TTZip create_archive failed for ZIP format");
    assert!(ttzip_zip_path.exists());

    // 2. System unzip -t integrity verification
    let test_output = Command::new(SYSTEM_UNZIP_PATH)
        .arg("-t")
        .arg(&ttzip_zip_path)
        .output()
        .expect("failed executing system unzip -t");
    let test_stdout = String::from_utf8_lossy(&test_output.stdout);
    assert!(
        test_output.status.success(),
        "unzip -t integrity test failed: {}",
        test_stdout
    );
    assert!(
        test_stdout.contains("No errors detected"),
        "expected 'No errors detected' in unzip -t, got: {}",
        test_stdout
    );

    // 3. System unzip extraction (/usr/bin/unzip -q -o <archive> -d <out_dir>)
    let unzip_output = Command::new(SYSTEM_UNZIP_PATH)
        .arg("-q")
        .arg("-o")
        .arg(&ttzip_zip_path)
        .arg("-d")
        .arg(&sandbox.system_out_dir)
        .output()
        .expect("failed executing system unzip extraction");
    assert!(
        unzip_output.status.success(),
        "system unzip extraction failed: {}",
        String::from_utf8_lossy(&unzip_output.stderr)
    );

    // 4. 5-Dimension Oracle Differential Comparison
    assert_differential_oracle_match(
        &sandbox.source_dir,
        &sandbox.system_out_dir,
        false,
        "bsdunzip",
        "zip",
    );
}

// MARK: - Bidirectional Symlink & Hardlink End-to-End Stress Test

#[test]
fn test_bidirectional_symlink_hardlink_permission_fidelity() {
    if !is_tool_available(SYSTEM_TAR_PATH) {
        eprintln!("[SKIP] System bsdtar not found, skipping bidirectional stress test.");
        return;
    }

    let sandbox = TestSandbox::new("ttzip_diff_bidi_stress");
    let src = &sandbox.source_dir;

    // 1. Setup multi-link and permission-sensitive file layout
    let data_file = src.join("data_target.bin");
    fs::write(&data_file, vec![0x5A; 16384]).unwrap();
    fs::set_permissions(&data_file, fs::Permissions::from_mode(0o644)).unwrap();

    let exec_file = src.join("runner.sh");
    fs::write(&exec_file, b"#!/bin/sh\nexit 0\n").unwrap();
    fs::set_permissions(&exec_file, fs::Permissions::from_mode(0o755)).unwrap();

    let ro_file = src.join("readonly.meta");
    fs::write(&ro_file, b"IMMUTABLE_METADATA_BLOCK").unwrap();
    fs::set_permissions(&ro_file, fs::Permissions::from_mode(0o444)).unwrap();

    let sub = src.join("sub");
    fs::create_dir_all(&sub).unwrap();
    let sub_symlink = sub.join("rel_symlink.bin");
    symlink("../data_target.bin", &sub_symlink).unwrap();

    let hardlink_entry = sub.join("hardlink_to_data.bin");
    fs::hard_link(&data_file, &hardlink_entry).unwrap();

    // 2. TTZip -> System Tar -> TTZip Roundtrip
    let tar_p1 = sandbox.root.join("stage1_ttzip.tar");
    let sources = sandbox.source_children();

    let create_opts = TTZipCreateOptions {
        format: TTZipArchiveFormat::Tar,
        level: TTZipCompressionLevel::Normal,
        ..Default::default()
    };
    UnifiedArchiveOrchestrator::create_archive(&sources, &tar_p1, &create_opts, 0)
        .expect("Stage 1 TTZip create_archive failed");

    // System unpacks Stage 1
    let s1_status = Command::new(SYSTEM_TAR_PATH)
        .arg("-xf")
        .arg(&tar_p1)
        .arg("-C")
        .arg(&sandbox.system_out_dir)
        .status()
        .expect("failed executing system bsdtar -xf on Stage 1");
    assert!(s1_status.success());

    // 3. System repacks Stage 1 output
    let tar_p2 = sandbox.root.join("stage2_system.tar");
    let s2_status = Command::new(SYSTEM_TAR_PATH)
        .arg("-cf")
        .arg(&tar_p2)
        .arg(".")
        .current_dir(&sandbox.system_out_dir)
        .status()
        .expect("failed executing system bsdtar -cf on Stage 2");
    assert!(s2_status.success());

    // 4. TTZip unpacks Stage 2 output
    let extract_opts = TTZipExtractOptions {
        preserve_permissions: true,
        overwrite_existing: true,
        ..Default::default()
    };
    UnifiedArchiveOrchestrator::extract_archive(&tar_p2, &sandbox.ttzip_out_dir, &extract_opts)
        .expect("Stage 2 TTZip extract_archive failed");

    // 5. Oracle verification against initial source tree
    assert_differential_oracle_match(
        &sandbox.source_dir,
        &sandbox.ttzip_out_dir,
        true,
        "roundtrip_bsdtar",
        "tar",
    );
}
