// SPDX-License-Identifier: BSD-3-Clause OR Apache-2.0
//
// Copyright (c) 2026 Witt Kung <witt.w.kung@gmail.com>
// All rights reserved.
//
// TTZip: High-performance native archiving and compression engine.

//! Comprehensive test suite for POSIX.1-2001 PAX extended header parsing, formatting,
//! self-consistent variable-length encoding, nanosecond timestamps, and GHSA-3cv2-h65g-fgmm security isolation.

use std::borrow::Cow;
use ttzip_engine::tar::header::TarHeader;
use ttzip_engine::tar::pax::{
    compute_pax_record_len, decimal_digits, format_pax_record, format_pax_time, parse_pax_records,
    parse_pax_time, PaxExtensionMap, PaxRecord, PaxZeroScanner, TarPaxError, MAX_PAX_RECORD_SIZE,
};

#[test]
fn test_decimal_digits_computation() {
    assert_eq!(decimal_digits(0), 1);
    assert_eq!(decimal_digits(1), 1);
    assert_eq!(decimal_digits(9), 1);
    assert_eq!(decimal_digits(10), 2);
    assert_eq!(decimal_digits(99), 2);
    assert_eq!(decimal_digits(100), 3);
    assert_eq!(decimal_digits(999), 3);
    assert_eq!(decimal_digits(1000), 4);
    assert_eq!(decimal_digits(9999), 4);
    assert_eq!(decimal_digits(10000), 5);
}

#[test]
fn test_pax_variable_length_self_consistent_boundaries() {
    // Test a wide range of value payload lengths across decimal digit boundary transitions
    for val_len in 0..1500 {
        let key = "test_key";
        let val = vec![b'x'; val_len];
        let encoded = format_pax_record(key, &val);

        // 1. Length of generated byte vector must match computed length exactly
        let expected_len = compute_pax_record_len(key.len(), val_len);
        assert_eq!(
            encoded.len(),
            expected_len,
            "Mismatch for val_len={val_len}: encoded={}, expected={expected_len}",
            encoded.len()
        );

        // 2. The decimal length prefix in ASCII must match the actual vector length
        let space_idx = encoded.iter().position(|&b| b == b' ').unwrap();
        let prefix_str = std::str::from_utf8(&encoded[..space_idx]).unwrap();
        let parsed_len: usize = prefix_str.parse().unwrap();
        assert_eq!(
            parsed_len,
            encoded.len(),
            "Prefix length {parsed_len} != actual vector length {} for val_len={val_len}",
            encoded.len()
        );

        // 3. Roundtrip parse with PaxZeroScanner
        let mut scanner = PaxZeroScanner::new(&encoded);
        let entry = scanner.next().unwrap().expect("Scanner parse failed");
        assert_eq!(entry.key, key);
        assert_eq!(entry.value, val.as_slice());
        assert_eq!(entry.total_len, encoded.len());
        assert!(scanner.next().is_none());
    }
}

#[test]
fn test_pax_boundary_record_lengths() {
    // Test specific boundary cases where record lengths approach 9, 10, 99, 100, 999, 1000
    let test_cases = [
        ("k", b"v".as_slice()),
        ("path", b"a".as_slice()),
        ("path", b"ab".as_slice()),
        ("path", b"abc".as_slice()),
        ("size", b"123456789".as_slice()),
        ("mtime", b"1700000000.123456789".as_slice()),
    ];

    for (k, v) in test_cases {
        let record_bytes = format_pax_record(k, v);
        let records = parse_pax_records(&record_bytes).expect("Failed to parse record");
        assert_eq!(records.len(), 1);
        assert_eq!(records[0].key, k);
        assert_eq!(records[0].value, v);
    }
}

#[test]
fn test_nanosecond_timestamp_parsing_and_formatting() {
    // 1. Standard full 9-digit nanoseconds
    let (s, ns) = parse_pax_time("1700000000.123456789");
    assert_eq!(s, 1700000000);
    assert_eq!(ns, 123456789);
    assert_eq!(format_pax_time(s, ns), "1700000000.123456789");

    // 2. 1-digit decimal (500ms / 500,000,000ns)
    let (s, ns) = parse_pax_time("1700000000.5");
    assert_eq!(s, 1700000000);
    assert_eq!(ns, 500000000);
    assert_eq!(format_pax_time(s, ns), "1700000000.500000000");

    // 3. 2-digit decimal (50ms / 50,000,000ns)
    let (s, ns) = parse_pax_time("1700000000.05");
    assert_eq!(s, 1700000000);
    assert_eq!(ns, 50000000);
    assert_eq!(format_pax_time(s, ns), "1700000000.050000000");

    // 4. 3-digit decimal (1ms / 1,000,000ns)
    let (s, ns) = parse_pax_time("1700000000.001");
    assert_eq!(s, 1700000000);
    assert_eq!(ns, 1000000);
    assert_eq!(format_pax_time(s, ns), "1700000000.001000000");

    // 5. Truncation of >9 digits (nanosecond clamp)
    let (s, ns) = parse_pax_time("1700000000.123456789999999");
    assert_eq!(s, 1700000000);
    assert_eq!(ns, 123456789);

    // 6. Negative timestamps (pre-1970 dates)
    let (s, ns) = parse_pax_time("-100.5");
    assert_eq!(s, -100);
    assert_eq!(ns, 500000000);
    assert_eq!(format_pax_time(s, ns), "-100.500000000");

    let (s, ns) = parse_pax_time("-86400");
    assert_eq!(s, -86400);
    assert_eq!(ns, 0);
    assert_eq!(format_pax_time(s, ns), "-86400");

    // 7. Pure integer seconds
    let (s, ns) = parse_pax_time("1609459200");
    assert_eq!(s, 1609459200);
    assert_eq!(ns, 0);
    assert_eq!(format_pax_time(s, ns), "1609459200");

    // 8. Zero timestamps
    let (s, ns) = parse_pax_time("0");
    assert_eq!(s, 0);
    assert_eq!(ns, 0);
    assert_eq!(format_pax_time(0, 0), "0");

    let (s, ns) = parse_pax_time("0.000000001");
    assert_eq!(s, 0);
    assert_eq!(ns, 1);
    assert_eq!(format_pax_time(0, 1), "0.000000001");

    // 9. Fault tolerance with invalid strings
    assert_eq!(parse_pax_time(""), (0, 0));
    assert_eq!(parse_pax_time("not_a_number"), (0, 0));
    assert_eq!(parse_pax_time("123.not_a_number"), (123, 0));
}

#[test]
fn test_huge_64bit_size_and_long_utf8_path() {
    let huge_size: u64 = 1099511627776; // 1 TB
    let long_utf8_path = "深度目录/子项目/归档文件_🌟_超级长路径_测试专用/very_long_path_segment_that_exceeds_one_hundred_bytes_limit_for_standard_tar_header_name_field/document.pdf";

    let mut map = PaxExtensionMap::new();
    map.set_path(long_utf8_path);
    map.set_size(huge_size);
    map.set_uid(10001);
    map.set_gid(10002);
    map.set_uname("wittkung");
    map.set_gname("developers");
    map.set_mtime(1700000000, 987654321);
    map.set_atime(1700000010, 111222333);
    map.set_ctime(1700000020, 444555666);
    map.set_linkpath("symlink/target/destination");

    // Serialize to PAX byte payload
    let payload = map.to_bytes();

    // Deserialize back from raw byte payload
    let parsed_map = PaxExtensionMap::from_slice(&payload).expect("Failed to parse PAX payload");

    assert_eq!(parsed_map.path(), Some(long_utf8_path));
    assert_eq!(parsed_map.size(), Some(huge_size));
    assert_eq!(parsed_map.uid(), Some(10001));
    assert_eq!(parsed_map.gid(), Some(10002));
    assert_eq!(parsed_map.uname(), Some("wittkung"));
    assert_eq!(parsed_map.gname(), Some("developers"));
    assert_eq!(parsed_map.mtime(), Some((1700000000, 987654321)));
    assert_eq!(parsed_map.atime(), Some((1700000010, 111222333)));
    assert_eq!(parsed_map.ctime(), Some((1700000020, 444555666)));
    assert_eq!(parsed_map.linkpath(), Some("symlink/target/destination"));
}

#[test]
fn test_ghsa_3cv2_h65g_fgmm_pax_size_isolation() {
    // Base 512-byte TAR header declaring size = 512 bytes
    let mut header = TarHeader::new();
    header.set_name("regular_file.bin");
    header.set_size(512);
    header.set_mode(0o644);
    header.set_uid(501);
    header.set_gid(20);
    header.set_mtime(1600000000);
    header.update_checksum();

    // 1. PAX record explicitly declaring huge size = 10_485_760 bytes (10 MB)
    let mut map_with_size = PaxExtensionMap::new();
    map_with_size.set_size(10_485_760);
    map_with_size.set_path("nested/isolated_file.bin");

    let entry = map_with_size.apply_to_entry(&header);
    // Security Invariant: PAX size MUST strictly override base header size!
    assert_eq!(
        entry.size, 10_485_760,
        "PAX size must take strict precedence over TarHeader size"
    );
    assert_eq!(entry.path, "nested/isolated_file.bin");
    assert_eq!(entry.uid, 501);

    // Also verify apply_to_header
    map_with_size.apply_to_header(&mut header);
    assert_eq!(header.size(), 10_485_760);
    assert_eq!(header.name(), "nested/isolated_file.bin");
    assert!(header.verify_checksum());

    // 2. PAX record without size attribute -> fallback to base header size
    let mut header2 = TarHeader::new();
    header2.set_name("fallback_file.bin");
    header2.set_size(8192);
    header2.update_checksum();

    let mut map_without_size = PaxExtensionMap::new();
    map_without_size.set_uname("admin");

    let entry2 = map_without_size.apply_to_entry(&header2);
    assert_eq!(
        entry2.size, 8192,
        "Entry must fallback to TarHeader size when PAX size is absent"
    );
    assert_eq!(entry2.path, "fallback_file.bin");
    assert_eq!(entry2.uname.as_deref(), Some("admin"));
}

#[test]
fn test_corrupted_pax_records_zero_panic_defense() {
    // 1. Truncated record: declared 100 bytes, buffer only has 25 bytes
    let truncated_data = b"100 path=truncated.txt\n";
    let mut scanner = PaxZeroScanner::new(truncated_data);
    let res = scanner.next().unwrap();
    assert!(matches!(res, Err(TarPaxError::TruncatedRecord { .. })));

    // 2. Missing space delimiter after length
    let no_space = b"30path=missing_space.txt\n";
    let mut scanner = PaxZeroScanner::new(no_space);
    let res = scanner.next().unwrap();
    assert!(matches!(res, Err(TarPaxError::MissingSpaceDelimiter)));

    // 3. Non-numeric decimal length
    let bad_len = b"xyz path=bad_length.txt\n";
    let mut scanner = PaxZeroScanner::new(bad_len);
    let res = scanner.next().unwrap();
    assert!(matches!(res, Err(TarPaxError::InvalidLength { .. })));

    // 4. Zero length
    let zero_len = b"0 path=zero_length.txt\n";
    let mut scanner = PaxZeroScanner::new(zero_len);
    let res = scanner.next().unwrap();
    assert!(matches!(res, Err(TarPaxError::InvalidLength { .. })));

    // 5. Length too small (declared 4, but prefix "4 a=\n" is 5)
    let too_small = b"4 a=\n";
    let mut scanner = PaxZeroScanner::new(too_small);
    let res = scanner.next().unwrap();
    assert!(matches!(res, Err(TarPaxError::LengthTooSmall { .. })));

    // 6. Missing equal sign ('=')
    let no_eq = b"19 path_without_eq\n";
    let mut scanner = PaxZeroScanner::new(no_eq);
    let res = scanner.next().unwrap();
    assert!(matches!(res, Err(TarPaxError::MissingEqualDelimiter)));

    // 7. Missing mandatory trailing newline ('\n')
    let no_newline = b"22 path=missing_nl.txt";
    let mut scanner = PaxZeroScanner::new(no_newline);
    let res = scanner.next().unwrap();
    assert!(matches!(res, Err(TarPaxError::MissingNewlineDelimiter)));

    // 8. Invalid UTF-8 sequence in keyword
    let bad_utf8_key = [b'1', b'2', b' ', 0xFF, 0xFE, b'=', b'v', b'a', b'l', b'u', b'e', b'\n'];
    let mut scanner = PaxZeroScanner::new(&bad_utf8_key);
    let res = scanner.next().unwrap();
    assert!(matches!(res, Err(TarPaxError::InvalidUtf8Key { .. })));

    // 9. Oversized record length exceeding security limit (MAX_PAX_RECORD_SIZE)
    let oversized_len_str = format!("{} path=huge\n", MAX_PAX_RECORD_SIZE + 100);
    let mut scanner = PaxZeroScanner::new(oversized_len_str.as_bytes());
    let res = scanner.next().unwrap();
    assert!(matches!(res, Err(TarPaxError::RecordTooLarge { .. })));

    // 10. Trailing TAR 512-byte zero block padding -> clean graceful termination
    let mut padded_block = Vec::new();
    padded_block.extend_from_slice(&format_pax_record("path", b"valid.txt"));
    padded_block.resize(512, 0); // pad remaining with NUL bytes

    let records = parse_pax_records(&padded_block).expect("Must ignore trailing zero padding");
    assert_eq!(records.len(), 1);
    assert_eq!(records[0].key, "path");
    assert_eq!(records[0].value, b"valid.txt");
}

#[test]
fn test_zero_copy_pax_zero_scanner_mechanics() {
    let payload = [
        format_pax_record("path", b"docs/readme.md"),
        format_pax_record("size", b"4096"),
        format_pax_record("mtime", b"1700000000.500000000"),
    ]
    .concat();

    let mut scanner = PaxZeroScanner::new(&payload);

    let e1 = scanner.next().unwrap().unwrap();
    assert_eq!(e1.key, "path");
    assert_eq!(e1.value_str().unwrap(), "docs/readme.md");
    assert_eq!(e1.value_lossy(), Cow::Borrowed("docs/readme.md"));

    let record1 = e1.to_record();
    assert_eq!(record1.key, "path");
    assert_eq!(record1.value, b"docs/readme.md");

    let e2 = scanner.next().unwrap().unwrap();
    assert_eq!(e2.key, "size");
    assert_eq!(e2.value_str().unwrap(), "4096");

    let e3 = scanner.next().unwrap().unwrap();
    assert_eq!(e3.key, "mtime");
    assert_eq!(e3.value_str().unwrap(), "1700000000.500000000");

    assert!(scanner.next().is_none());
}

#[test]
fn test_pax_extension_map_manipulation_and_overrides() {
    let mut map = PaxExtensionMap::new();
    assert!(map.is_empty());
    assert_eq!(map.len(), 0);

    map.insert("custom.key", b"initial_val".as_slice());
    assert_eq!(map.get_str("custom.key"), Some("initial_val"));
    assert_eq!(map.len(), 1);

    // Overwrite existing key
    map.insert("custom.key", b"updated_val".as_slice());
    assert_eq!(map.get_str("custom.key"), Some("updated_val"));
    assert_eq!(map.len(), 1);

    // Remove key
    let removed = map.remove("custom.key");
    assert_eq!(removed, Some(b"updated_val".to_vec()));
    assert!(!map.contains_key("custom.key"));
    assert!(map.is_empty());

    // Construct from records with duplicate keys (last record wins)
    let records = vec![
        PaxRecord::new("path", "first/path.txt"),
        PaxRecord::new("size", "100"),
        PaxRecord::new("path", "final/path.txt"),
    ];
    let map = PaxExtensionMap::from_records(records);
    assert_eq!(map.path(), Some("final/path.txt"));
    assert_eq!(map.size(), Some(100));
}
