// SPDX-License-Identifier: BSD-3-Clause OR Apache-2.0
//
// Copyright (c) 2026 Witt Kung <witt.w.kung@gmail.com>
// All rights reserved.
//
// TTZip: High-performance native archiving and compression engine.

//! Mozilla UniFFI Password Vault Key Derivation and Authenticated Encryption Layer.
//!
//! Provides typed, memory-sanitized bindings for PBKDF2-HMAC-SHA256 key derivation,
//! HMAC-SHA256 verifier calculation, and AES-256-GCM payload encryption / decryption.

use super::types::TTZipError;
use std::sync::atomic::{compiler_fence, Ordering};
use zeroize::Zeroize;

/// Derives a 256-bit symmetric encryption key using PBKDF2-HMAC-SHA256.
#[uniffi::export]
pub fn vault_derive_key(
    password: String,
    salt: Vec<u8>,
    iterations: u32,
) -> Result<Vec<u8>, TTZipError> {
    if password.is_empty() && salt.is_empty() {
        return Err(TTZipError::EngineError { code: -1 });
    }
    if iterations == 0 {
        return Err(TTZipError::EngineError { code: -2 });
    }

    let mut derived_key = vec![0u8; 32];
    let res = crate::crypto::vault::pbkdf2_hmac_sha256(
        password.as_bytes(),
        &salt,
        iterations,
        &mut derived_key,
    );

    match res {
        Ok(_) => Ok(derived_key),
        Err(_) => {
            derived_key.zeroize();
            compiler_fence(Ordering::SeqCst);
            Err(TTZipError::EngineError { code: -3 })
        }
    }
}

/// Encrypts an arbitrary payload using AES-256-GCM with a fresh random 12-byte IV.
///
/// Output format: `[12-byte IV] || [Ciphertext] || [16-byte Tag]`
#[uniffi::export]
pub fn vault_encrypt_payload(key: Vec<u8>, payload: Vec<u8>) -> Result<Vec<u8>, TTZipError> {
    if key.len() != 32 {
        return Err(TTZipError::EngineError { code: -1 });
    }

    let mut key_arr = [0u8; 32];
    key_arr.copy_from_slice(&key);

    let mut iv = [0u8; 12];
    if crate::crypto::vault::get_random_bytes(&mut iv).is_err() {
        key_arr.zeroize();
        compiler_fence(Ordering::SeqCst);
        return Err(TTZipError::EngineError { code: -2 });
    }

    let mut ciphertext = vec![0u8; payload.len()];
    let mut tag = [0u8; 16];

    let enc_res = crate::crypto::vault::aes256_gcm_encrypt(
        &key_arr,
        &iv,
        &payload,
        &[],
        &mut ciphertext,
        &mut tag,
    );

    key_arr.zeroize();
    compiler_fence(Ordering::SeqCst);

    if enc_res.is_err() {
        ciphertext.zeroize();
        return Err(TTZipError::EngineError { code: -3 });
    }

    let mut result = Vec::with_capacity(12 + ciphertext.len() + 16);
    result.extend_from_slice(&iv);
    result.extend_from_slice(&ciphertext);
    result.extend_from_slice(&tag);
    Ok(result)
}

/// Decrypts an authenticated payload generated by `vault_encrypt_payload`.
///
/// Input format: `[12-byte IV] || [Ciphertext] || [16-byte Tag]`
#[uniffi::export]
pub fn vault_decrypt_payload(
    key: Vec<u8>,
    encrypted_data: Vec<u8>,
) -> Result<Vec<u8>, TTZipError> {
    if key.len() != 32 {
        return Err(TTZipError::EngineError { code: -1 });
    }
    if encrypted_data.len() < 28 {
        return Err(TTZipError::EngineError { code: -2 });
    }

    let mut key_arr = [0u8; 32];
    key_arr.copy_from_slice(&key);

    let mut iv = [0u8; 12];
    iv.copy_from_slice(&encrypted_data[..12]);

    let cipher_len = encrypted_data.len() - 28;
    let ciphertext = &encrypted_data[12..12 + cipher_len];

    let mut tag = [0u8; 16];
    tag.copy_from_slice(&encrypted_data[12 + cipher_len..]);

    let mut plaintext = vec![0u8; cipher_len];
    let res = crate::crypto::vault::aes256_gcm_decrypt(
        &key_arr,
        &iv,
        ciphertext,
        &[],
        &tag,
        &mut plaintext,
    );

    key_arr.zeroize();
    compiler_fence(Ordering::SeqCst);

    match res {
        Ok(_) => Ok(plaintext),
        Err(_) => {
            plaintext.zeroize();
            compiler_fence(Ordering::SeqCst);
            Err(TTZipError::InvalidPassword)
        }
    }
}

/// Computes HMAC-SHA256 verifier hash of derived key and salt for master password verification.
#[uniffi::export]
pub fn vault_compute_verifier(key: Vec<u8>, salt: Vec<u8>) -> String {
    let mut key_arr = key;
    let hash = crate::crypto::vault::hmac_sha256(&key_arr, &salt);
    key_arr.zeroize();
    compiler_fence(Ordering::SeqCst);
    hash.iter().map(|b| format!("{:02x}", b)).collect()
}
