// SPDX-License-Identifier: BSD-3-Clause OR Apache-2.0
//
// Copyright (c) 2026 Witt Kung <witt.w.kung@gmail.com>
// All rights reserved.
//
// TTKit: High-performance cross-platform system utility foundation.

use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Serialize, Deserialize)]
pub struct CatalogEntry {
    pub key: String,
    #[serde(default)]
    pub description: Option<String>,
    pub translations: BTreeMap<String, String>,
    #[serde(default)]
    pub placeholders: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct CatalogContract {
    #[serde(default)]
    pub namespace: String,
    pub entries: BTreeMap<String, CatalogEntry>,
}

/// Generates Rust compile-time static slices from a JSON contract.
pub fn generate_rust_catalogs(contract_path: &Path, out_dir: &Path) -> Result<()> {
    let content = fs::read_to_string(contract_path)?;
    let contract: CatalogContract = serde_json::from_str(&content)?;

    let languages = ["en", "zh-Hans", "zh-Hant", "ja", "de", "fr", "es"];
    
    for lang in languages {
        let rust_lang_name = lang.replace("-", "_").to_lowercase();
        let file_path = out_dir.join(format!("{}.rs", rust_lang_name));
        
        let mut out = String::from("// Auto-generated by tt-l10n-tools. DO NOT EDIT.\n\n");
        out.push_str("pub static STRINGS: &[(&str, &str)] = &[\n");

        let mut sorted_entries: Vec<(&String, &String)> = Vec::new();
        for (k, entry) in &contract.entries {
            if let Some(trans) = entry.translations.get(lang) {
                sorted_entries.push((k, trans));
            } else if let Some(fallback) = entry.translations.get("en") {
                sorted_entries.push((k, fallback));
            }
        }
        sorted_entries.sort_by_key(|&(k, _)| k);

        for (k, v) in sorted_entries {
            let escaped_v = v.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n");
            out.push_str(&format!("    (\"{}\", \"{}\"),\n", k, escaped_v));
        }
        out.push_str("];\n");

        fs::write(file_path, out)?;
    }

    Ok(())
}

/// Generates Swift strongly-typed enum namespaces from a JSON contract.
pub fn generate_swift_enums(contract_path: &Path, out_file: &Path) -> Result<()> {
    let content = fs::read_to_string(contract_path)?;
    let contract: CatalogContract = serde_json::from_str(&content)?;

    let mut out = String::from("// Auto-generated by tt-l10n-tools. DO NOT EDIT.\n\n");
    out.push_str("import Foundation\n\n");
    out.push_str("public protocol LocaleKeyProtocol: Sendable {\n");
    out.push_str("    var rawKey: String { get }\n");
    out.push_str("}\n\n");
    out.push_str("public extension LocaleKeyProtocol where Self: RawRepresentable, RawValue == String {\n");
    out.push_str("    @inlinable var rawKey: String { rawValue }\n");
    out.push_str("}\n\n");
    out.push_str("public enum L10n {\n");

    let mut namespaces: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    for (k, _) in &contract.entries {
        let parts: Vec<&str> = k.split('.').collect();
        let ns = if parts.len() > 1 { parts[0] } else { "common" };
        let case_name = if parts.len() > 1 { parts[1..].join("_") } else { parts[0].to_string() };
        
        let camel_case = to_camel_case(&case_name);
        let escaped_case = escape_swift_keyword(&camel_case);
        namespaces.entry(ns.to_string()).or_default().push((escaped_case, k.clone()));
    }

    for (ns, cases) in namespaces {
        let type_name = to_pascal_case(&ns);
        out.push_str(&format!("    public enum {}: String, LocaleKeyProtocol, CaseIterable {{\n", type_name));
        for (case_name, raw_key) in cases {
            out.push_str(&format!("        case {} = \"{}\"\n", case_name, raw_key));
        }
        out.push_str("    }\n\n");
    }

    out.push_str("}\n");
    fs::write(out_file, out)?;
    Ok(())
}

fn escape_swift_keyword(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "import", "default", "init", "class", "struct", "enum", "protocol", "extension",
        "self", "Self", "let", "var", "func", "return", "throw", "throws", "try",
        "catch", "break", "continue", "fallthrough", "switch", "case", "where", "while",
        "for", "in", "repeat", "if", "else", "guard", "as", "is", "nil", "true", "false",
        "typealias", "operator", "precedencegroup", "defer", "open", "public", "internal",
        "fileprivate", "private", "subscript", "associatedtype"
    ];
    if KEYWORDS.contains(&name) {
        format!("`{}`", name)
    } else {
        name.to_string()
    }
}

fn to_camel_case(s: &str) -> String {
    let parts: Vec<&str> = s.split('_').collect();
    let mut res = String::new();
    for (i, p) in parts.iter().enumerate() {
        if i == 0 {
            res.push_str(&p.to_lowercase());
        } else {
            let mut c = p.chars();
            if let Some(f) = c.next() {
                res.push(f.to_ascii_uppercase());
                res.push_str(&c.as_str().to_lowercase());
            }
        }
    }
    if res.is_empty() {
        s.to_lowercase()
    } else {
        res
    }
}

fn to_pascal_case(s: &str) -> String {
    let mut res = String::new();
    for p in s.split('_') {
        let mut c = p.chars();
        if let Some(f) = c.next() {
            res.push(f.to_ascii_uppercase());
            res.push_str(&c.as_str().to_lowercase());
        }
    }
    if res.is_empty() {
        s.to_string()
    } else {
        res
    }
}
