# SPDX-License-Identifier: BSD-3-Clause OR Apache-2.0
#
# Copyright (c) 2026 MetastudyLine Inc. <contact@metastudyline.com>
# All rights reserved.
#
# TTZip Android Device Subsystem

load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

exports_files(["Cargo.toml"])

rust_library(
    name = "ttzip_device_android",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "ttzip_device_android",
    edition = "2021",
    deps = [
        "@crates//:adb_client",
        "@crates//:bytes",
        "@crates//:log",
        "@crates//:mdns-sd",
        "@crates//:nusb",
        "@crates//:parking_lot",
        "@crates//:serde",
        "@crates//:thiserror",
        "@crates//:tokio",
        "@crates//:zeroize",
    ],
)
