# SPDX-License-Identifier: BSD-3-Clause OR Apache-2.0
#
# Copyright (c) 2026 MetastudyLine Inc. <contact@metastudyline.com>
# All rights reserved.
#
# TTZip Core Rust Workspace Root Package

package(default_visibility = ["//visibility:public"])

exports_files([
    "Cargo.toml",
    "Cargo.lock",
])
