[workspace]
members = [
    "ttzip-engine",
    "ttzip-glue",
    "ttzip-tui",
    "ttzip-python",
]
resolver = "2"

[workspace.package]
version = "1.0.0"
authors = ["Witt Kung <witt.w.kung@gmail.com>"]
license = "BSD-3-Clause OR Apache-2.0"
repository = "https://github.com/wittkung/ttzip-core"
homepage = "https://github.com/wittkung/ttzip-core"
documentation = "https://github.com/wittkung/ttzip-core"
edition = "2021"
keywords = ["compression", "zip", "7z", "simd", "archive"]
categories = ["compression", "command-line-utilities", "filesystem"]

[profile.release]
opt-level = 3
lto = false
codegen-units = 1
panic = "unwind"
strip = false

[profile.test]
opt-level = 3
debug = 1

[workspace.lints.rust]
unsafe_code = "allow"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(feature, values("gil-refs"))'] }

[workspace.lints.clippy]
not_unsafe_ptr_arg_deref = "allow"
needless_range_loop = "allow"

