#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause OR Apache-2.0
#
# Copyright (c) 2026 Witt Kung <witt.w.kung@gmail.com>
# All rights reserved.
#
# TTZip: High-performance native archiving and compression engine.

"""
clean_license_headers.py - Deterministic License & Header Deduplication Engine for TTZip
Safely cleans legacy/stacked license headers and injects exact 1-tier canonical headers.
"""

import argparse
import os
import re
import sys
from pathlib import Path

# Directories and files to strictly ignore (third-party, autogenerated, fixtures)
IGNORE_DIRS = {
    ".git", ".build", "target", "node_modules", ".worktrees", ".swiftpm", 
    "dist", "artifacts", "checkouts", "Vendor", "upstream"
}

IGNORE_PATH_CONTAINS = [
    "CTTZipBridge/zopfli",
    "CTTZipBridge/snappy",
    "CTTZipBridge/fast-lzma2",
    "CTTZipBridge/lzfse",
    "Tests/fixtures",
    "Tests/TTZipTests/Fixtures",
    "org/junit",
]

IGNORE_EXACT_FILES = {
    "ttzip_engineFFI.h",
    "Package.resolved",
}

GPL_PATH_SEGMENTS = {
    "apple",
    "TTZipApp",
    "TTZipFinderSync",
    "TTZipQuickLook",
    "TTZipAppTests",
}

EXTENSION_COMMENT_MAP = {
    ".swift": "//",
    ".c": "//",
    ".h": "//",
    ".m": "//",
    ".mm": "//",
    ".cpp": "//",
    ".hpp": "//",
    ".rs": "//",
    ".go": "//",
    ".java": "//",
    ".ts": "//",
    ".js": "//",
    ".py": "#",
    ".sh": "#",
    ".rb": "#",
}

def determine_license_tier(filepath: str) -> str:
    full_path = os.path.abspath(filepath).replace("\\", "/")
    parts = set(full_path.split("/"))
    if parts.intersection(GPL_PATH_SEGMENTS):
        return "GPL-3.0-or-later"
    return "BSD-3-Clause OR Apache-2.0"

def generate_header(tier: str, comment_char: str) -> str:
    p = comment_char
    lines = [
        f"{p} SPDX-License-Identifier: {tier}",
        f"{p}",
        f"{p} Copyright (c) 2026 Witt Kung <witt.w.kung@gmail.com>",
        f"{p} All rights reserved.",
        f"{p}",
        f"{p} TTZip: High-performance native archiving and compression engine.",
        ""
    ]
    return "\n".join(lines)

def strip_existing_header(content: str, comment_char: str):
    lines = content.splitlines(True)
    i = 0
    shebang = ""
    if lines:
        first_line = lines[0]
        if first_line.startswith("#!") or first_line.startswith("// swift-tools-version:"):
            shebang = first_line
            i = 1

    license_line_re = re.compile(
        r"^\s*(" + re.escape(comment_char) + r")?\s*("
        r"SPDX-License-Identifier:|"
        r"Copyright\s*(\(c\))?|"
        r"All rights reserved|"
        r"TTZip: High-performance|"
        r"TTZip\s*\(including|"
        r"GNU General Public License|"
        r"Licensed under|"
        r"This file is part of TTZip"
        r")",
        re.IGNORECASE
    )

    idx = i
    while idx < len(lines):
        line = lines[idx]
        stripped = line.strip()

        if stripped == "" or stripped == comment_char:
            peek_has_license = False
            for p in range(idx + 1, min(idx + 15, len(lines))):
                if license_line_re.search(lines[p]):
                    peek_has_license = True
                    break
                elif lines[p].strip() != "" and not lines[p].strip().startswith(comment_char):
                    break
            if peek_has_license:
                idx += 1
                continue
            else:
                break

        if license_line_re.search(line):
            idx += 1
            continue

        if stripped.startswith(comment_char) and not (stripped.startswith(comment_char + "/") or stripped.startswith(comment_char + "!")):
            peek_has_license = False
            for p in range(idx + 1, min(idx + 15, len(lines))):
                if license_line_re.search(lines[p]):
                    peek_has_license = True
                    break
            if peek_has_license:
                idx += 1
                continue

        break

    body_lines = lines[idx:]
    while body_lines and (body_lines[0].strip() == "" or body_lines[0].strip() == comment_char):
        body_lines.pop(0)

    body = "".join(body_lines)
    return shebang, body

def process_file(filepath: str, repo_root: str, dry_run: bool = False) -> bool:
    rel_path = os.path.relpath(filepath, repo_root)
    norm_path = rel_path.replace("\\", "/")

    # Check ignore rules
    if any(ign in norm_path for ign in IGNORE_PATH_CONTAINS):
        return False
    if os.path.basename(filepath) in IGNORE_EXACT_FILES:
        return False

    ext = os.path.splitext(filepath)[1].lower()
    if ext not in EXTENSION_COMMENT_MAP:
        return False

    comment_char = EXTENSION_COMMENT_MAP[ext]
    tier = determine_license_tier(filepath)
    canonical_header = generate_header(tier, comment_char)

    try:
        with open(filepath, "r", encoding="utf-8") as fp:
            original_content = fp.read()
    except Exception as e:
        print(f"  [ERROR] Cannot read {rel_path}: {e}")
        return False

    shebang, body = strip_existing_header(original_content, comment_char)

    if shebang:
        new_content = shebang + canonical_header + "\n" + body
    else:
        new_content = canonical_header + "\n" + body

    if new_content != original_content:
        if not dry_run:
            with open(filepath, "w", encoding="utf-8") as fp:
                fp.write(new_content)
        return True
    return False

def main():
    parser = argparse.ArgumentParser(description="Clean and standardize license headers.")
    parser.add_argument("--dry-run", action="store_true", help="Report files that would change without writing.")
    parser.add_argument("--check", action="store_true", help="Exit with code 1 if any file needs cleaning.")
    parser.add_argument("--repo-root", default=".", help="Root directory of the repository.")
    args = parser.parse_args()

    repo_root = os.path.abspath(args.repo_root)
    changed_files = []
    scanned_count = 0

    for root, dirs, files in os.walk(repo_root):
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]
        for fn in files:
            ext = os.path.splitext(fn)[1].lower()
            if ext in EXTENSION_COMMENT_MAP:
                scanned_count += 1
                filepath = os.path.join(root, fn)
                if process_file(filepath, repo_root, dry_run=(args.dry_run or args.check)):
                    changed_files.append(os.path.relpath(filepath, repo_root))

    print(f"Scanned {scanned_count} active source files across repo.")
    print(f"Identified {len(changed_files)} files requiring header remediation.")

    if changed_files:
        for cf in changed_files[:20]:
            print(f"  [FIXED] {cf}")
        if len(changed_files) > 20:
            print(f"  ... and {len(changed_files) - 20} more files.")

    if args.check and changed_files:
        print(f"\n[FAIL] {len(changed_files)} files have non-standard/duplicate headers.")
        sys.exit(1)

    print("\n[SUCCESS] License header remediation complete.")

if __name__ == "__main__":
    main()
