[package]
name = "ttzip-node"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "High-throughput native archiving and compression engine for Node.js (N-API)"

[lib]
crate-type = ["cdylib"]

[dependencies]
ttzip-engine = { path = "../ttzip-engine", version = "1.0.0" }
napi = { version = "2.16", default-features = false, features = ["napi4", "async", "tokio_rt"] }
napi-derive = "2.16"

[build-dependencies]
napi-build = "2.1"
