[package]
name = "ttzip-bindgen"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "UniFFI binding generator CLI for TTZip"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[[bin]]
name = "uniffi-bindgen"
path = "src/main.rs"

[dependencies]
uniffi = { version = "0.28", features = ["cli"] }
